<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflection.proto
#

namespace Xhtkyy\GrpcServer\Reflection;


interface ServerReflectionInterface
{
    // grpc service name
    public const SERVICE_NAME = "grpc.reflection.v1alpha.ServerReflection";

	// grpc metadata class
	public const METADATA_CLASS = \Xhtkyy\GrpcServer\Reflection\GPBMetadata\Reflection::class;

	// grpc dependency file
	public const DEPENDENCY = ["reflection.proto"];

    /**
     * input ServerReflectionRequest
     * output ServerReflectionResponse
     * @param ServerReflectionRequest $request
     * @return ServerReflectionResponse
     */
    public function ServerReflectionInfo(ServerReflectionRequest $request): ServerReflectionResponse;

}
