<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/Health/health.proto
# @see https://github.com/crayxn/grpc-server

namespace Xhtkyy\GrpcServer\Health;

interface HealthInterface
{
    // grpc service name
    public const SERVICE_NAME = "grpc.health.v1.Health";

	// grpc metadata class
	public const METADATA_CLASS = \Xhtkyy\GrpcServer\Health\GPBMetadata\Health::class;

	// grpc dependency file
	public const DEPENDENCY = ["health.proto"];

    /**
    * @param HealthCheckRequest $request
    * @return HealthCheckResponse
    */
    public function Check(HealthCheckRequest $request): HealthCheckResponse;


    /**
     * output HealthCheckResponse
     * @param HealthCheckRequest $request
     * @return HealthCheckResponse
     */
    public function Watch(HealthCheckRequest $request): HealthCheckResponse;

}
